---
- name: Install netplan
  apt: name=netplan.io state=present force_apt_get=yes update_cache=yes


- name: Copy netplan configs
  copy:
      src: config.yaml
      dest: /etc/netplan/
      owner: root
      group: root
      backup: True
  register: netplan


- name: Applying netplan settings
  command: sudo netplan apply
  when: netplan.changed
